### ISSUE TITLE
start error：You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by yang302** [zhongs/react-marquee#1]
![image](https://user-images.githubusercontent.com/20217508/51449939-77c9db80-1d69-11e9-9b07-dde526af5c60.png)

**Comment by zhongs** [comment]
Thanks for your attention

I joined the example, which is configured with the environment.[examples](https://github.com/zhongs/react-marquee/tree/master/examples)
Run it，look package.json

> npm run examples

**Comment by yang302** [comment]
thanks!  I had got it!         
but when it has only one or two data, it scrolls not very well!
